server:
  port: 10017
  max-http-header-size: 8192
spring:
  application:
    name: pf-resume
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 10003
        dashboard: localhost:10002
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.resume.client: DEBUG # feign日志
user:
  server: localhost:10015
recruit:
  server: localhost:10016
debug: true