server:
  port: 10017
  max-http-header-size: 8192
spring:
  application:
    name: pf-resume
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      host: 47.94.248.38
      port: 27017
      database: personfilter
  redis:
    host: 47.94.248.38
    timeout: 5000ms
    port: 6379
logging:
  level:
    com.stalary.pf.resume.client: DEBUG # feign日志
user:
  server: localhost:10015
recruit:
  server: localhost:10016