server:
  port: 10016
  max-http-header-size: 8192
spring:
  application:
    name: pf-recruit
  cloud:
    nacos:
      discovery:
        server-addr: 59.111.95.232:8848
    sentinel:
      transport:
        port: 10003
        dashboard: 59.111.95.232:10002
  zipkin:
    base-url: http://59.111.95.232:9411/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.recruit.client: DEBUG # feign日志