server:
  port: 10016
  max-http-header-size: 8192
spring:
  application:
    name: pf-recruit
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.recruit.client: DEBUG # feign日志
user:
  server: localhost:10015