server:
  port: 10013
  max-http-header-size: 8192
spring:
  application:
    name: pf-message
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
push:
  server: localhost:10011
