server:
  port: 10011
  max-http-header-size: 8192
spring:
  application:
    name: pf-push
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: localhost:10001/
  sleuth:
    sampler:
      probability: 1.0

