server:
  port: 10015
  max-http-header-size: 8192
  user: http://usercenter.stalary.com
  debug: true
spring:
  application:
    name: pf-user
  cloud:
    nacos:
      discovery:
        server-addr: 59.111.95.232:8848
    sentinel:
      transport:
        port: 10003
        dashboard: 59.111.95.232:10002
  zipkin:
    base-url: http://59.111.95.232:9411/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.user.client: DEBUG # feign日志
com:
  stalary:
    easydoc:
      path: com.stalary.pf.user
      contact: stalary@163.com
      description: pf-user
      source: false
      open: true
      name: pf-user