server:
  port: 10015
  max-http-header-size: 8192
  user: http://usercenter.stalary.com
  debug: true
spring:
  application:
    name: pf-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.user.client: DEBUG # feign日志
message:
  server: localhost:10013
recruit:
  server: localhost:10016