server:
  port: 10015
  max-http-header-size: 8192
  user: http://usercenter.stalary.com
  debug: true
spring:
  data:
    elasticsearch:
      cluster-name:
  application:
    name: pf-user
  cloud:
    nacos:
      discovery:
        server-addr: nacos.stalary.com
    sentinel:
      transport:
        port: 10003
        dashboard: sentinel.stalary.com
  zipkin:
    base-url: http://zipkin.stalary.com
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.user.client: DEBUG # feign日志
com:
  stalary:
    easydoc:
      path: com.stalary.pf.user
      contact: stalary@163.com
      description: pf-user
      source: false
      open: true
      name: pf-user