server:
  port: 10005
  max-http-header-size: 8192
  user: http://usercenter.stalary.com
  debug: true
spring:
  application:
    name: pf-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://47.94.248.38:3306/personfilter?characterEncoding=utf-8&useSSL=false
    username: root
    password: li197910
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 47.94.248.38
    timeout: 5000ms
    port: 6379
gateway:
  server: localhost:10000