server:
  port: 10015
  max-http-header-size: 8192
  user: http://usercenter.stalary.com
  debug: true
spring:
  application:
    name: pf-user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://47.94.248.38:3306/personfilter?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: li197910
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1 # 最小空闲连接数
      maximum-pool-size: 15 # 最大连接数量
      pool-name: user-pool
      connection-test-query: SELECT 1 # 测试连接
  redis:
    host: 47.94.248.38
    timeout: 5000ms
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
message:
  server: localhost:10013
recruit:
  server: localhost:10016