server:
  port: 10000
  user: http://usercenter.stalary.com
  max-http-header-size: 8192
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 59.111.95.232:8848
  zipkin:
    base-url: http://59.111.95.232:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: pf-gateway
logging:
  level:
    com.stalary.pf.gateway.client: DEBUG # feign日志
    com.alibaba.nacos.client.naming: WARN