server:
  port: 10000
  user: http://usercenter.stalary.com
  debug: true
  max-http-header-size: 8192
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:10001
        predicates:
        - Path=/push/**
      - id: host_route
        uri: http://localhost:10002
        predicates:
        - Path=/outside/**
      - id: host_route
        uri: http://localhost:10003
        predicates:
        - Path=/message/**
      - id: host_route
        uri: http://localhost:10004
        predicates:
        - Path=/message/**
      - id: host_route
        uri: http://localhost:10007
        predicates:
        - Path=/resume/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: pf-gateway
logging:
  level:
    com.stalary.pf.gateway.client: DEBUG # feign日志
pf:
  authList: /message/user/get, /message/read, /message/user/send