server:
  port: 10000
  user: http://usercenter.stalary.com
  max-http-header-size: 8192
spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:10011
        predicates:
        - Path=/push/**
      - id: host_route
        uri: http://localhost:10012
        predicates:
        - Path=/outside/**
      - id: host_route
        uri: http://localhost:10013
        predicates:
        - Path=/message/**
      - id: host_route
        uri: http://localhost:10015
        predicates:
        - Path=/user/**
      - id: host_route
        uri: http://localhost:10016
        predicates:
        - Path=/recruit/**
      - id: host_route
        uri: http://localhost:10016
        predicates:
        - Path=/company/**
      - id: host_route
        uri: http://localhost:10017
        predicates:
        - Path=/resume/**
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:10001
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: pf-gateway
logging:
  level:
    com.stalary.pf.gateway.client: DEBUG # feign日志
    com.alibaba.nacos.client.naming: WARN