server:
  port: 10014
  max-http-header-size: 8192
spring:
  application:
    name: pf-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:10001/
  sleuth:
    sampler:
      probability: 1.0
com:
  stalary:
    lightmq:
      consumer: true
      order: true
      group: master
      auto: true
      url: http://120.24.5.178:8001
push:
  server: localhost:10011
outside:
  server: localhost:10012
message:
  server: localhost:10013
user:
  server: localhost:10015
recruit:
  server: localhost:10016
resume:
  server: localhost:10017
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志