server:
  port: 10004
  max-http-header-size: 8192
spring:
  application:
    name: pf-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志
com:
  stalary:
    lightmq:
      consumer: true
      order: true
      group: master
      auto: true
      url: http://120.24.5.178:8001
push:
  server: localhost:10001
outside:
  server: localhost:10002
message:
  server: localhost:10003
user:
  server: localhost:10005
recruit:
  server: localhost:10006
resume:
  server: localhost:10007