server:
  port: 10014
  max-http-header-size: 8192
spring:
  application:
    name: pf-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 59.111.95.232:8848
  zipkin:
    base-url: http://59.111.95.232:9411/
  sleuth:
    sampler:
      probability: 1.0
logging:
  level:
    com.stalary.pf.consumer.client: DEBUG # feign日志
com:
  stalary:
    lightmq:
      consumer: true
      order: true
      group: master
      auto: true
      url: http://120.24.5.178:8001